apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: my-cluster
  namespace: flux-system
spec:
  interval: 30s
  path: "./clusters/my-cluster"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
